apiVersion: v1
kind: Service
metadata:
  name: abs-guide-svc
  namespace: abs-guide
spec:
  type: LoadBalancer
  selector:
    app: abs-guide-app
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 80