apiVersion: apps/v1
kind: Deployment
metadata:
  name: abs-guide
  namespace: abs-guide
  labels:
    app: abs-guide
spec:
  replicas: 2
  selector:
    matchLabels:
      app: abs-guide
  template:
    metadata:
      labels:
        app: abs-guide
    spec:
      containers:
      - name: abs-guide
        image: damola12345/abs-guide:latest
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.2"
        ports:
          - containerPort: 80
          # livenessProbe:
          #   httpGet:
          #     path: /status
          #     port: 80
          #   initialDelaySeconds: 3
          #   periodSeconds: 3